export const languages = [
  { id: "rd", name: "Random" },
  { id: "ab", name: "Abkhazian" },
  { id: "af", name: "Afrikaans" },
  { id: "sq", name: "Albanian" },
  { id: "am", name: "Amharic" },
  { id: "ar", name: "Arabic" },
  { id: "an", name: "Aragonese" },
  { id: "hy", name: "Armenian" },
  { id: "az", name: "Azerbaijani" },
  { id: "bm", name: "Bambara" },
  { id: "ba", name: "Bashkir" },
  { id: "eu", name: "Basque" },
  { id: "be", name: "Belarusian" },
  { id: "bn", name: "Bengali" },
  { id: "bh", name: "Bihari languages" },
  { id: "bi", name: "Bislama" },
  { id: "bs", name: "Bosnian" },
  { id: "bg", name: "Bulgarian" },
  { id: "my", name: "Burmese" },
  { id: "ca", name: "Catalan, Valencian" },
  { id: "zh", name: "Chinese" },
  { id: "co", name: "Corsican" },
  { id: "hr", name: "Croatian" },
  { id: "cs", name: "Czech" },
  { id: "da", name: "Danish" },
  { id: "nl", name: "Dutch, Flemish" },
  { id: "en", name: "English" },
  { id: "et", name: "Estonian" },
  { id: "fj", name: "Fijian" },
  { id: "fi", name: "Finnish" },
  { id: "fr", name: "French" },
  { id: "ff", name: "Fulah" },
  { id: "gd", name: "Gaelic, Scottish Gaelic" },
  { id: "gl", name: "Galician" },
  { id: "ka", name: "Georgian" },
  { id: "de", name: "German" },
  { id: "ki", name: "Gikuyu, Kikuyu" },
  { id: "el", name: "Greek (Modern)" },
  { id: "kl", name: "Greenlandic, Kalaallisut" },
  { id: "gn", name: "Guarani" },
  { id: "gu", name: "Gujarati" },
  { id: "ht", name: "Haitian, Haitian Creole" },
  { id: "he", name: "Hebrew" },
  { id: "hi", name: "Hindi" },
  { id: "hu", name: "Hungarian" },
  { id: "is", name: "Icelandic" },
  { id: "id", name: "Indonesian" },
  { id: "ga", name: "Irish" },
  { id: "it", name: "Italian" },
  { id: "ja", name: "Japanese" },
  { id: "kr", name: "Kanuri" },
  { id: "kk", name: "Kazakh" },
  { id: "kv", name: "Komi" },
  { id: "kg", name: "Kongo" },
  { id: "ko", name: "Korean" },
  { id: "ku", name: "Kurdish" },
  { id: "lo", name: "Lao" },
  { id: "la", name: "Latin" },
  { id: "lv", name: "Latvian" },
  { id: "lb", name: "Letzeburgesch, Luxembourgish" },
  { id: "li", name: "Limburgish, Limburgan, Limburger" },
  { id: "ln", name: "Lingala" },
  { id: "lt", name: "Lithuanian" },
  { id: "mk", name: "Macedonian" },
  { id: "mg", name: "Malagasy" },
  { id: "ms", name: "Malay" },
  { id: "ml", name: "Malayalam" },
  { id: "mt", name: "Maltese" },
  { id: "mi", name: "Maori" },
  { id: "mr", name: "Marathi" },
  { id: "ro", name: "Moldovan, Moldavian, Romanian" },
  { id: "mn", name: "Mongolian" },
  { id: "na", name: "Nauru" },
  { id: "nv", name: "Navajo, Navaho" },
  { id: "nd", name: "Northern Ndebele" },
  { id: "ne", name: "Nepali" },
  { id: "no", name: "Norwegian" },
  { id: "pa", name: "Panjabi, Punjabi" },
  { id: "fa", name: "Persian" },
  { id: "pl", name: "Polish" },
  { id: "pt", name: "Portuguese" },
  { id: "rm", name: "Romansh" },
  { id: "ru", name: "Russian" },
  { id: "sm", name: "Samoan" },
  { id: "sc", name: "Sardinian" },
  { id: "sr", name: "Serbian" },
  { id: "sk", name: "Slovak" },
  { id: "sl", name: "Slovenian" },
  { id: "so", name: "Somali" },
  { id: "es", name: "Spanish, Castilian" },
  { id: "su", name: "Sundanese" },
  { id: "sw", name: "Swahili" },
  { id: "ss", name: "Swati" },
  { id: "sv", name: "Swedish" },
  { id: "tl", name: "Tagalog" },
  { id: "ty", name: "Tahitian" },
  { id: "tg", name: "Tajik" },
  { id: "ta", name: "Tamil" },
  { id: "th", name: "Thai" },
  { id: "bo", name: "Tibetan" },
  { id: "tr", name: "Turkish" },
  { id: "tk", name: "Turkmen" },
  { id: "ug", name: "Uighur, Uyghur" },
  { id: "uk", name: "Ukrainian" },
  { id: "ur", name: "Urdu" },
  { id: "uz", name: "Uzbek" },
  { id: "vi", name: "Vietnamese" },
  { id: "cy", name: "Welsh" },
  { id: "fy", name: "Western Frisian" },
  { id: "xh", name: "Xhosa" },
  { id: "yo", name: "Yoruba" },
  { id: "za", name: "Zhuang, Chuang" },
];
